# Generated by Django 5.0.6 on 2024-07-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('dob', models.CharField(default='', max_length=25)),
                ('address', models.CharField(default='', max_length=150)),
                ('emailid', models.CharField(default='', max_length=100)),
                ('mobileno', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('photograph', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
