# Generated by Django 4.2.4 on 2023-09-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('icon', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('dob', models.CharField(default='', max_length=25)),
                ('address', models.CharField(default='', max_length=150)),
                ('emailid', models.CharField(default='', max_length=100)),
                ('mobileno', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('photograph', models.ImageField(upload_to='static/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnumber', models.CharField(default='', max_length=200)),
                ('question', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.category')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttimings', models.CharField(default='', max_length=100)),
                ('endtimings', models.CharField(default='', max_length=100)),
                ('days', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=45)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subquestionnumber', models.CharField(default='', max_length=200)),
                ('subquestion', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.category')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.doctors')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('username', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),
                ('dob', models.CharField(default='', max_length=200)),
                ('emailid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mobileno', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.city')),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientstate', to='Medassistapp.states')),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='Medassistapp.states'),
        ),
        migrations.AddField(
            model_name='city',
            name='states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.states'),
        ),
    ]
