# Generated by Django 4.2.4 on 2023-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='states',
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
