# Generated by Django 3.2.5 on 2023-08-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='Medassistapp.states'),
        ),
    ]
