# Generated by Django 4.2.4 on 2023-09-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0002_alter_doctors_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timings',
            name='days',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='timings',
            name='endtimings',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='timings',
            name='starttimings',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='timings',
            name='status',
            field=models.CharField(default='', max_length=45),
        ),
    ]
