# Generated by Django 4.2.4 on 2023-09-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0004_questions_subquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('emailid', models.CharField(default='', max_length=150)),
                ('mobileno', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=25)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
